# Generated by Django 5.2.6 on 2025-09-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_highlightcard_reasontolove'),
    ]

    operations = [
        migrations.CreateModel(
            name='VetConsultationReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='vet_icons/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
