# Generated by Django 5.2.6 on 2025-09-28 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_vetconsultationreason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='doctors/')),
            ],
        ),
    ]
