# Generated by Django 5.2.6 on 2025-09-27 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_is_available_alter_brand_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintype',
            name='breed',
        ),
    ]
