# Generated by Django 5.2.6 on 2025-09-28 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_maintype_breed'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='top-deals/')),
                ('link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('main_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_deals', to='shop.maintype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
