# Generated by Django 5.2.6 on 2025-09-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='life_stage',
            field=models.CharField(blank=True, choices=[('puppy', 'Puppy'), ('adult_dog', 'Adult Dog'), ('senior_dog', 'Senior Dog'), ('adult_cat', 'Adult Cat'), ('senior_cat', 'Senior Cat')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=2, null=True),
        ),
    ]
